config/routes.rb
Rails.application.routes.draw do
  root 'stars#index'
  resources :stars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/star.rb
class Star < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stars_controller.rb
class StarsController < ApplicationController
  def index
    @stars = Star.all
  end
  def new
    @star = Star.new
  end

  def create
    Star.create(star_params)
    redirect_to root_path
  end

  private

  def star_params
    params.require(:star).permit(:name, :desription)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stars_helper.rb
module StarsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stars/index.html.erb
<h1>Shoot for the Stars!</h1>
<br />
<br />
<div class="text-center">
<%= link_to 'Add Star', new_star_path, class: 'btn btn-success' %>
</div>
<br />
<br />


<%= @stars.each do |star| %>
<div class="row">
<div class="booyah-box offset-5">
  <h3><%= star.name %></h3><br />
  <p><%= star.desription %></p>
  <br />
  <br />
  </div>
</div>
  <% end %>

app/views/stars/new.html.erb
<h1>Add a New Star</h1>
<div class="booyah-box col-8 offset-2">
<%= simple_form_for @star do |f| %>
  <%= f.input :name %>
  <%= f.input :desription %>
  <br />
  <%= f.submit "Create", class: 'btn btn-primary' %>
  <br />
</div>
  <% end %>